root = "."
tmp_dir = "tmp"
env_files = [".env"]

[build]
cmd = "go build -gcflags=all=\"-N -l\" -o ./tmp/main ."
entrypoint = ["./tmp/main", "worker"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "api-docs"]
exclude_regex = ["_test\\.go"]
stop_on_error = true

[log]
time = false

[misc]
clean_on_exit = true
